display_errors=Off
display_startup_errors=Off
log_errors=On
expose_php=Off
memory_limit=256M
max_execution_time=30
upload_max_filesize=8M
post_max_size=10M
opcache.enable=1
opcache.validate_timestamps=0
opcache.memory_consumption=128
opcache.max_accelerated_files=20000
zend.exception_ignore_args=On
